// <auto-generated />
using System;
using FirstApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstApp.Migrations
{
    //[DbContext(typeof(FirstAppContext))]
    partial class FirstAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstApp.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnName("personID");

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("Type")
                        .HasColumnName("type");

                    b.Property<int?>("Usertypeid");

                    b.HasKey("PersonId");

                    b.HasIndex("Usertypeid");

                    b.ToTable("Person");
                });

            //modelBuilder.Entity("FirstApp.Models.UserType", b =>
            //    {
            //        b.Property<int>("Usertypeid")
            //            .HasColumnName("usertypeid");

            //        b.Property<string>("Type")
            //            .IsRequired()
            //            .HasColumnName("type")
            //            .HasMaxLength(15)
            //            .IsUnicode(false);

            //        b.HasKey("Usertypeid");

            //        b.ToTable("userType");
            //    });

            modelBuilder.Entity("FirstApp.Models.Person", b =>
                {
                    b.HasOne("FirstApp.Models.UserType")
                        .WithMany("Person")
                        .HasForeignKey("Usertypeid");
                });
#pragma warning restore 612, 618
        }
    }
}
